name: SecurityPipeline

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  horusec-security:
    name: horusec-security
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
      
    - name: Ensure Docker is running
      run: |
        sudo systemctl start docker
        sudo systemctl enable docker
        docker --version

    - name: Install Horusec
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest

    - name: Running Horusec Security
      run: |
        horusec start -p="./" -i="**/node_modules/**,**/dist/**,**/build/**" -e="true" -o="json" -O="./horusec-report.json" --disable-docker="true"
      
    - name: Upload scan results
      uses: actions/upload-artifact@v4
      if: always() # Run even when the test fails due to detected vulnerabilities.
      with:
        name: horusec-security-report
        path: ./horusec-report.json
        retention-days: 7 # Optional: how long to keep the artifact (default is 90 days)
